version: '3.3'

services:
  pg:
    container_name: iot_db
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=gomusic
      - POSTGRES_USER=gomusic
      - POSTGRES_DB=gomusic
    ports:
      - 5432:5432
  rabbitmq:
    container_name: iot_rmq
    image: rabbitmq:3.9.13-management
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=secret
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 5672:5672
      - 8080:15672
networks:
  default:
    driver: "bridge"