version: '3.3'

services:
  db:
    container_name: iot_db
    image: mariadb
    environment:
      - MYSQL_DATABASE=iot
      - MYSQL_USER=iot
      - MYSQL_PASSWORD=iot
      - MYSQL_ROOT_PASSWORD=iot
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: iot_phpmyadmin
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=iot
      - PMA_PASSWORD=iot
  rabbitmq:
    container_name: iot_rmq
    image: rabbitmq:3.9.13-management
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=secret
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 5672:5672
      - 8080:15672
networks:
  default:
    driver: "bridge"